spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://user-center-aws.cposeiwwc1o4.us-east-1.rds.amazonaws.com:3306/user_center
    username: root
    password: Aa123456

  session:
    timeout: 86400



